### ISSUE TITLE
Propose additions/changes to the building block spec for v2

### ISSUE THREAD

**Issue by taylordowns2000** [GovStackWorkingGroup/bb-workflow#24]
So far, the workflow team has proposed that the next version of the spec should include the _conversion_ of more of the functional requirements into APIs. Is there anything else that we'd like to add/change in the spec?

1. conversion of functional requirements to API specs (where relevant)
2. addition of IAM apis?
3. wait for messages to appear from org X, org Y, validate sender

**Comment by FaraiMutero** [comment]
In light of the GovStack vision to empower the actual implementors of this building blocks, as opposed to developers only, would recommend the following points:

1. Sharpen the focus on desktop design work on BPMN models and output of a "ready-to-deploy" BMPN model file as a project artefact.
2. Provide specifications on Workflow BB support of appropriate end user message types, like email to facilitate workflows that have conditions or activities that can be completed via a structured email, for example.
3. Provide specifications on long-running workflow processes, time-outs and escalation mechanisms to prevent and manage workflows that take and extra-ordinary amount of time to complete
4. Provide specifications on the management, storage and invokation of adapters (or mediators) to facilitate "plug-and-play" interoperability between between a Workflow BB implementation and other well established third party systems
5. Promote the adoption of other related BPMN models like DMN (https://docs.camunda.org/manual/7.17/reference/dmn/) and CMMN (https://docs.camunda.org/manual/7.17/reference/cmmn11/) to strengthen the capabilities of a Workflow BB implementation
6. Expand the scope of the Workflow BB sandbox  examples to faciitate end-to-end testing based on selected DIAL use-cases e.g "Post Partum and Infant Care"

**Comment by taylordowns2000** [comment]
moved to jira: https://govstack-global.atlassian.net/browse/GOV-577
