### ISSUE TITLE
Add images to specification

### ISSUE THREAD

**Issue by taylordowns2000** [GovStackWorkingGroup/bb-workflow#29]
Currently, the images all point to the [Google Doc spec](https://docs.google.com/document/d/1TIQ756eWauQLNeSWUqfm5dpDz_wJsesfZgXBiWXLx9w/edit#) and don't render in markdown/gitbook.

A search for `gd2md-html alert` yields 14 broken image URLs across 5 files. We should store all images in `/spec/images`, pending confirmation from @rachellawson , and update the links accordingly:

- [ ] `spec/3-terminology.md`
- [ ] `spec/6-functional-requirements.md`
- [ ] `spec/7-data-structures.md`
- [ ] `spec/9-workflows.md`
- [ ] `spec/10-other-resources.md`

**Comment by rachellawson** [comment]
@Ayushdidit would be best to comment on the procedure he followed to extract images from the google doc but GitBook would, by default, place embedded images into the /spec/.gitbook/media folder once uploaded, FYI

**Comment by rachellawson** [comment]
Not quite. So, if you look at the published (in development) pages at https://govstack.gitbook.io/bb-workflow/6-functional-requirements you’ll see that the export from google docs contains some “comments” that tell you about replacing certain sections with actual images.
You’ll need to edit those, upload an image (ideally from source) into the spec folder and reference it from there

**Comment by taylordowns2000** [comment]
Ok, right, I think we're actually saying the same thing 🤣 . See my original comment here: https://github.com/GovStackWorkingGroup/bb-workflow/issues/29#issue-1354460883

**Comment by taylordowns2000** [comment]
this has been moved to: https://govstack-global.atlassian.net/jira/software/c/projects/GOV/boards/22?modal=detail&selectedIssue=GOV-546
